[package]
name = "leptos_datatable"
license = "MIT"
version = "0.1.0"
edition = "2021"
description = "A leptos component for creating tables with data validation."

[dependencies]
leptos = { version = "0.6.9", features = ["csr", "nightly"] }
